query queryData($condition:MetricsCondition!,$labels:[String!]!,$duration:Duration!){readLabeledMetricsValues:readLabeledMetricsValues(condition:$condition,labels:$labels,duration:$duration){label values{values{value}}}}
